config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "get_dones#index", as: :get_dones
  post "lists/:id", to: "lists#status", as: :status
  resources :lists do
    resources :items
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/get_done.rb
class GetDone < ApplicationRecord
  has_many :lists
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  has_many :items, dependent: :destroy

  accepts_nested_attributes_for :items, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/get_dones_controller.rb
class GetDonesController < ApplicationController
  def index
    @lists = List.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = @list.items.build(items_params)
    
  end

  def create
    @list = List.find(params[:list_id])

    @item = @list.items.build(items_params)

    if @item.save
      redirect_to list_path(@list), notice: 'Item added to the list !'
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  private

  def items_params
    params.require(:item).permit(:name, :status)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @list = List.find(params[:id])
    @items = @list.items.find_by(id: params[:id])
  end

  def new
    @list = List.new
    5.times{@list.items.build}
    # items << @list.items.build
  end

  def create
    Rails.logger.debug "PARAMS => #{params.inspect}"
    @list = List.new(list_params)
    if @list.save
      redirect_to get_dones_path, notice: "Saved com sucesso !"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list, notice: "List updated !"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to get_dones_path, notice: 'List deleted !'
  end

  def status
    @list = List.find(params[:id])
      if @list.update(status: true)
        redirect_to get_dones_path, notice: 'List marked as complete !'
      else
        render :show, status: :unprocessable_entity
      end
  end

  private

  def list_params
    params.require(:list).permit(:title, items_attributes: [ :name, :id, :status, :_destroy ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_done_helper.rb
module GetDoneHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/to_do_list_helper.rb
module ToDoListHelper
end

app/views/get_done/index.html.erb
<h1> To Do List 🚀</h1>
<ol>
  <% @lists.each do |list| %>
    <li><%= list.title %></li>
      <%# <ul> - = list.item </ul> %>
  <% end %>
</ol>

app/views/get_done/list.html.erb
<h1>Our first view 🚀</h1>

app/views/get_dones/index.html.erb
<div class="container header">
  <div><h1> To Do List 🚀</h1></div>
  <p> <%= link_to "Create new list", new_list_path  %> </p>
</div>

<div class="container card-align">
  <% @lists.each do |list| %>
    <div class="card-index">
      <%= link_to list do %>
        <p><%= list.title %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/get_dones/list.html.erb
<h1>Our first view 🚀</h1>

<%= simple_form_for [@get_done, @list] do |f| %>
  <%= f.input :title %>
  <%= f.input :item, as: :booleans %>
  <%= f.submit 'Schedule your band session' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/list/new.html.erb
<h1>Our first view 🚀</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :title %>
  <%= f.input :item, as: :boolean %>
  <%= f.submit 'Schedule your band session' %>
<% end %>

app/views/lists/edit.html.erb
<div class="container header">
  <div class="title">
    <h1>Edit your list 🚀</h1>
  </div>
  <div class="list-nav">
    <p> <%= link_to 'Back to list', get_dones_path(@list) %> </p>
  </div>
</div>

<div class="items-card col-8">
  <%= simple_form_for(@list, html: { multipart: true }) do |f| %>
    <div class="edit-card">
      <%= f.input :title, placeholder: @list.title %>
    </div>
    <div class="edit-card">
      <%= f.simple_fields_for :items do |items_form| %>
        <%= items_form.input :name %>
      <% end %>
    </div>
    <div class="edit-card">
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container header">
  <div class="title">
    <h1>Our first view 🚀</h1>
  </div>
  <div class="list-nav">
    <p> <%= link_to 'Back to list', get_dones_path(@list) %> </p>
  </div>
</div>

<div class="items-card col-8">
  <%= simple_form_for @list do |f| %>
    <div class="edit-card">
      <%= f.error_notification %>
      <%= f.input :title %>
    </div>
    <div class="edit-card">
      <%= f.simple_fields_for :items do |items_form|%>
        <%= items_form.input :name %>
      <% end %>
    </div>
    <div class="edit-card">
        <%= f.submit 'Save' %>
      <% end %>
    </div>
</div>

app/views/lists/show.html.erb
  <%#= simple_form_for @items do |f| %>
    <%#= f.association :status, as: :boolean %>
  <%# end %>

<div class="container header">
  <div class="title">
    <h1> <%= @list.title %> </h1>
  </div>
  <div class="list-nav">
    <p> <%= link_to "Lists", get_dones_path %> </p>
    <p> <%= link_to "Done", status_path %> </p>
    <p> <%= link_to "Edit List", edit_list_path %> </p>
    <p> <%= link_to "Delete", list_path(@list), data: {turbo_method: :delete, turbo_cofirm: "Are you sure?"} %> </p>
  </div>
</div>

<div class="items-card col-8">
  <% @list.items.each do |item| %>
    <p class="items"> <%= item.name %> </p>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="container footer">
  <div class="footer-links">
    <a href="https://github.com/hugoborgesuk"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/hugo-b-248b79115/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Created by Hugo Borges
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
  </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div> %>